### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by youngjae41** [anish-bhattacharya/ViT-for-quadrotor-obstacle-avoidance#1]
Thank you for sharing the excellent code. I would like to test it using an actual drone, as described in the paper. When can I expect to be able to test this code? Thank you.

**Comment by anish-bhattacharya** [comment]
Hello! I've made an major update to the provided code and instructions. We now include a ROS1 package `depthfly` that includes a python rosnode for subscribing to a d435 depth camera, running our model on the depth images, and outputting velocity commands. Please check it out, and let me know if you have any questions!

P.S. If you need a quadrotor flight stack to use more generally, please refer to [KumarLab autonomy stack](https://github.com/KumarRobotics/kr_autonomous_flight) or [RPG autonomy stack](https://github.com/uzh-rpg/agilicious) or [PX4 autonomy stack](https://github.com/PX4/PX4-Autopilot).
