### ISSUE TITLE
RuntimeError: Input must have 3 dimensions, got 2 

### ISSUE THREAD

**Issue by yiichu03** [anish-bhattacharya/ViT-for-quadrotor-obstacle-avoidance#4]
Hello,
After finish Installation, I ran  : `bash launch_evaluation.bash 1 vision`
However, I encountered the following error,which keeps occurring repeatedly, but the program does not terminate:
```
ERROR] [1730705986.547447, 1730705951.373007]: bad callback: <bound method AgilePilotNode.img_callback of <__main__.AgilePilotNode object at 0x7f95ff7016a0>>
Traceback (most recent call last):
  ...
  RuntimeError: input must have 3 dimensions, got 2
```
 I haven't modified any of the original code, so I'm wondering if you could provide some guidance on how to resolve this issue.  
Thank you very much!!
![image](https://github.com/user-attachments/assets/c6efaf93-daa5-43e4-b3c9-92e89a5cab18)
![屏幕截图 2024-11-04 154445](https://github.com/user-attachments/assets/4c180c4c-1b7d-4adf-8837-afdd0061d3d0)

**Comment by yiichu03** [comment]
Hi,

I wanted to provide an update regarding the error I encountered previously. After modifying the `launch_evaluation.bash` script to change the model_type from `ViTLSTM `to another model name, such as `UNet`, the error related to the image callback was resolved. 

However, I've noticed a new issue: the drone ascends a short distance and then stops, and the final output states, `"You did not reach the goal!"`
![image](https://github.com/user-attachments/assets/00fe6767-bc63-4192-8e1d-24e92de76b11)

I followed the README instructions and downloaded the `pretrained weights` as directed. 

Could anyone provide insights into why the drone might be stopping or not reaching its goal? Any help would be greatly appreciated!

Thank you!

**Comment by Golden-Pigeon** [comment]
Have encountered the same problem. The reason is that in old version PyTorch like 1.10.x (in my environment), the input of LSTM must have 3 dimensions. While in newer version of PyTorch, for example 2.7.x, it can have only 2 dimensions. So use `out = out.unsqueeze(1)` before 'out,h = self.lstm(out, X[3])' may solve this problem.
